server:
  port: 8090

mongodb:
  primary:
    uri: 192.168.126.147:27017
    username: test1
    password: test1
    database: test1
  admin:
    uri: 192.168.126.147:27017
    username: admin
    password: admin
    database: admin

